### ISSUE TITLE
Works on Cemu 2.4

### ISSUE THREAD

**Issue by Aeternalia** [Alexander-Lancellott/MH3U-MH3G-HP-Overlay-For-WiiU-Emulator#1]
Hey, thanks so much for porting this! I just wanted to report that it works perfectly on Cemu 2.4. On top of that, the overlay works even in fullscreen for me without using the borderless method.

**Comment by Alexander-Lancellott** [comment]
Glad to hear it works perfectly on cemu 2.4 too
